export enum RabbitMQ {
  JuntaReceptoraVotosQueue = 'junta_receptora_votos',
}

export enum JuntaReceptoraVotosMSG {
  CREATE = 'CREATE_JUNTA_RECEPTORA_VOTOS',
  UPDATE = 'UPDATE_JUNTA_RECEPTORA_VOTOS',
  DELETE = 'DELETE_JUNTA_RECEPTORA_VOTOS',
  FIND_ALL = 'FIND_JUNTAS_RECEPTORA_VOTOS',
  FIND_ALL_BY_MUNICIPIO = 'FIND_ALL_BY_MUNICIPIO',
  FIND_ONE = 'FIND_JUNTA_RECEPTORA_VOTOS',
  FIND_ONE_BY_CODE = 'FIND_JUNTA_RECEPTORA_VOTOS_BY_CODE',
  SET_STATUS_JRV = 'SET_STATUS_JRV',
  GET_MEMBERS = 'GET_MEMBERS',
  GET_MEMBERS_BY_JRV = 'GET_MEMBERS_BY_JRV',
  GET_MEMBER_BY_ID = 'GET_MEMBER_BY_ID',
  GET_MEMBER_BY_USER_ID = 'GET_MEMBER_BY_USER_ID',
  CREATE_MEMBER = 'CREATE_MEMBER',  
  UPDATE_MEMBER = 'UPDATE_MEMBER',
  DELETE_MEMBER = 'DELETE_MEMBER',
  SET_STATUS_JRV_MEMBER = 'SET_STATUS_JRV_MEMBER',
}